# Generated by Django 5.0.6 on 2025-02-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CallTranscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("call_sid", models.CharField(max_length=34)),
                ("transcript", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_final", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "caller_id",
                    models.CharField(
                        max_length=34, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("phone_number", models.CharField(max_length=20, null=True)),
                ("contentUser", models.TextField()),
                ("contentAI", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
